extends Node
## i18n — EN primary for web MVP; TR ready.

var _strings: Dictionary = {
	"en": {
		"app_name": "Isometric Pixel Map",
		"tool_pen": "Pen",
		"tool_erase": "Erase",
		"tool_fill": "Fill",
		"layer_ground": "Ground",
		"layer_props": "Props",
		"export_png": "Export PNG",
		"save_json": "Save JSON",
		"load_json": "Load JSON",
		"new_map": "New map",
		"undo": "Undo",
		"redo": "Redo",
		"about": "About",
		"hint": "Paint · Scroll zoom · RMB / Space pan",
		"about_body": "Retro isometric pixel map editor. Paint a mini world, export PNG or JSON. No account needed.",
		"about_free": "Free & open source. Paint · export · share.",
		"shortcuts": "P pen · E erase · F fill · B brush · G grid · 1 ground · 2 props · Ctrl+Z/Y undo/redo · Ctrl+S save · Ctrl+E PNG · Ctrl+N new · Maps = starters",
		"saved": "JSON downloaded",
		"loaded": "Map loaded",
		"exported": "PNG downloaded",
		"load_fail": "Could not load map",
		"save_fail": "Could not save",
		"export_fail": "PNG export failed",
		"grid_on": "Grid on",
		"grid_off": "Grid off",
		"template_loaded": "Template",
		"share_copied": "Share link copied!",
		"brush_size": "Brush",
	},
	"tr": {
		"app_name": "Isometric Pixel Map",
		"tool_pen": "Kalem",
		"tool_erase": "Silgi",
		"tool_fill": "Doldur",
		"layer_ground": "Zemin",
		"layer_props": "Üst",
		"export_png": "PNG İndir",
		"save_json": "JSON Kaydet",
		"load_json": "JSON Yükle",
		"new_map": "Yeni harita",
		"template_loaded": "Şablon",
		"undo": "Geri al",
		"redo": "İleri al",
		"about": "Hakkında",
		"hint": "Boya · Zoom tekerlek · Kaydır: sağ tık / Space",
		"about_body": "Retro izometrik pixel harita editörü. Mini dünya boya, PNG veya JSON indir. Hesap yok.",
		"about_free": "Ücretsiz ve açık kaynak. Boya · dışa aktar · paylaş.",
		"shortcuts": "P kalem · E silgi · F doldur · B fırça · G ızgara · 1 zemin · 2 üst · Ctrl+Z/Y · Ctrl+S kaydet · Ctrl+E PNG · Ctrl+N yeni · Maps = şablonlar",
		"saved": "JSON indirildi",
		"loaded": "Harita yüklendi",
		"exported": "PNG indirildi",
		"load_fail": "Harita yüklenemedi",
		"save_fail": "Kaydedilemedi",
		"export_fail": "PNG export başarısız",
		"grid_on": "Izgara açık",
		"grid_off": "Izgara kapalı",
		"share_copied": "Paylaşım linki kopyalandı!",
		"brush_size": "Fırça",
	},
}


func t(key: String) -> String:
	var locale: String = str(Game.settings.get("locale", "en"))
	var bag: Dictionary = _strings.get(locale, _strings["en"])
	return str(bag.get(key, _strings["en"].get(key, key)))
