extends Node
## i18n — EN primary for web MVP; TR ready.

var _strings: Dictionary = {
	"en": {
		"app_name": "Isometric Pixel Map",
		"tool_pen": "Pen",
		"tool_erase": "Erase",
		"tool_fill": "Fill",
		"layer_ground": "Ground",
		"layer_props": "Props",
		"export_png": "Export PNG",
		"save_json": "Save JSON",
		"load_json": "Load JSON",
		"new_map": "New map",
		"undo": "Undo",
		"redo": "Redo",
		"about": "About",
		"hint": "Paint · Scroll zoom · RMB / Space pan",
		"about_body": "Retro isometric pixel map editor. Paint a mini world, export PNG or JSON. No account needed.",
		"about_free": "Free & open source. Paint · export · share.",
		"shortcuts": "P pen · E erase · F fill · B brush · G grid · 1 ground · 2 props · Ctrl+Z/Y undo/redo · Ctrl+S save · Ctrl+E PNG · Ctrl+N new · Maps = starters",
		"saved": "JSON downloaded",
		"loaded": "Map loaded",
		"exported": "PNG downloaded",
		"load_fail": "Could not load map",
		"save_fail": "Could not save",
		"export_fail": "PNG export failed",
		"grid_on": "Grid on",
		"grid_off": "Grid off",
		"template_loaded": "Template",
		"share_copied": "Share link copied!",
		"share_too_large": "Map too large — share link would be too long",
		"share_web_only": "Share link works in web export only",
		"brush_size": "Brush",
		"welcome": "Welcome! Drag to paint, right-click to pan.",
		"title_placeholder": "Map title...",
		"maps": "Maps",
		"load": "Load",
		"save": "Save",
		"share": "Share",
		"brush_1x": "1×",
		"brush_3x": "3×",
		"brush_5x": "5×",
	},
	"tr": {
		"app_name": "Isometric Pixel Map",
		"tool_pen": "Kalem",
		"tool_erase": "Silgi",
		"tool_fill": "Doldur",
		"layer_ground": "Zemin",
		"layer_props": "Nesneler",
		"export_png": "PNG İndir",
		"save_json": "JSON Kaydet",
		"load_json": "JSON Yükle",
		"new_map": "Yeni harita",
		"template_loaded": "Şablon yüklendi",
		"undo": "Geri al",
		"redo": "Yinele",
		"about": "Hakkında",
		"hint": "Boya · Scroll yakınlaştır · Sağ tık / Boşluk kaydır",
		"about_body": "Retro izometrik piksel harita editörü. Mini bir dünya çiz, PNG veya JSON olarak dışa aktar. Hesap gerekmez.",
		"about_free": "Ücretsiz & açık kaynak. Çiz · dışa aktar · paylaş.",
		"shortcuts": "P kalem · E silgi · F doldur · B fırça · G ızgara · 1 zemin · 2 nesneler · Ctrl+Z/Y geri/yinele · Ctrl+S kaydet · Ctrl+E PNG · Ctrl+N yeni · Haritalar = şablonlar",
		"saved": "JSON indirildi",
		"loaded": "Harita yüklendi",
		"exported": "PNG indirildi",
		"load_fail": "Harita yüklenemedi",
		"save_fail": "Kaydedilemedi",
		"export_fail": "PNG dışa aktarma başarısız",
		"grid_on": "Izgara açık",
		"grid_off": "Izgara kapalı",
		"share_copied": "Paylaşım linki kopyalandı!",
		"share_too_large": "Harita çok büyük — paylaşım linki çok uzun olur",
		"share_web_only": "Paylaşım linki yalnızca web sürümünde çalışır",
		"brush_size": "Fırça",
		"welcome": "Hoş geldin! Sürükleyerek çiz, sağ tık ile kaydır.",
		"title_placeholder": "Harita başlığı...",
		"maps": "Haritalar",
		"load": "Yükle",
		"save": "Kaydet",
		"share": "Paylaş",
		"brush_1x": "1×",
		"brush_3x": "3×",
		"brush_5x": "5×",
	},
}


func t(key: String) -> String:
	var locale: String = str(Game.settings.get("locale", "en"))
	var bag: Dictionary = _strings.get(locale, _strings["en"])
	return str(bag.get(key, _strings["en"].get(key, key)))
